# Generated by Django 4.0.3 on 2022-04-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNo', models.CharField(max_length=15)),
                ('Address', models.TextField()),
            ],
        ),
    ]
