# Generated by Django 4.0.3 on 2022-04-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoneContact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='userContact',
        ),
    ]
